DROP DATABASE IF EXISTS QuanLiGuiXe;
CREATE DATABASE QuanLiGuiXe;
\c QuanLiGuiXe;
CREATE TABLE QuanLiChungCu(
	ID_NguoiQuanLi  CHARACTER(5) NOT NULL,
	Ten CHARACTER VARYING(50) NOT NULL,
	GioiTinh CHARACTER VARYING(10) NOT NULL,
	NgaySinh DATE NOT NULL,
	DiaChi CHARACTER VARYING(80) NOT NULL,
	SDT CHARACTER VARYING(20) NOT NULL,
	CONSTRAINT pk_nguoiquanli PRIMARY KEY(ID_NguoiQuanLi)
);


CREATE TABLE BaoVe(
	ID_BaoVe CHARACTER(5) NOT NULL,
	Ten CHARACTER VARYING(50) NOT NULL,
	GioiTinh CHARACTER VARYING(10) NOT NULL,
	NgaySinh DATE NOT NULL,
	DiaChi CHARACTER VARYING(80) NOT NULL,
	SDT CHARACTER VARYING(20) NOT NULL,
	Username CHARACTER VARYING(30) NOT NULL,
	Password CHARACTER VARYING(30) NOT NULL,
	CONSTRAINT pk_baove PRIMARY KEY(ID_BaoVe)	
);


CREATE TABLE QuanLi(
	ID_NguoiQuanLi CHARACTER(5) NOT NULL,
	ID_BaoVe CHARACTER(5) NOT NULL,
	CONSTRAINT pk_quanli PRIMARY KEY(ID_NguoiQuanLi,ID_BaoVe),
	CONSTRAINT fk_quanli FOREIGN KEY(ID_NguoiQuanLi) REFERENCES QuanLiChungCu(ID_NguoiQuanLi),
	CONSTRAINT fk_baove FOREIGN KEY(ID_BaoVe) REFERENCES BaoVe(ID_BaoVe)
);


CREATE TABLE TheTu(
	ID_TheTu CHARACTER(5) NOT NULL,
	BienSo CHARACTER VARYING(15) NOT NULL,
	ID_NguoiGui CHARACTER(5),
	VeThang BOOLEAN NOT NULL,
	NgayDangKyVe DATE DEFAULT CURRENT_DATE,
	NgayHetHanVe DATE DEFAULT CURRENT_DATE,
	CONSTRAINT pk_thetu PRIMARY KEY(ID_TheTu)
);


CREATE TABLE XeDangKyVe(
	BienSo CHARACTER VARYING(15) NOT NULL,
	ID_NguoiGui character(5) NOT NULL,
	LoaiXe CHARACTER VARYING(50) NOT NULL,
	CONSTRAINT pk_xedangky PRIMARY KEY(BienSo)
);


ALTER TABLE TheTu
ADD CONSTRAINT fk_bienso FOREIGN KEY(BienSo) REFERENCES XeDangKyVe(BienSo);


CREATE TABLE NguoiDangKyVe(
	ID_NguoiGui CHARACTER(5) NOT NULL,
	Ten CHARACTER VARYING(50) NOT NULL,
	NgaySinh DATE NOT NULL,
	DiaChi CHARACTER VARYING(80) NOT NULL,
	SDT CHARACTER VARYING(20) NOT NULL,
	CONSTRAINT pk_nguoigui PRIMARY KEY(ID_NguoiGui)
);

ALTER TABLE XeDangKyVe
ADD CONSTRAINT fk_nguoigui_xe FOREIGN KEY(ID_NguoiGui) REFERENCES NguoiDangKyVe(ID_NguoiGui);

ALTER TABLE TheTu
ADD CONSTRAINT fk_nguoigui_thetu FOREIGN KEY(ID_NguoiGui) REFERENCES NguoiDangKyVe(ID_NguoiGui);



CREATE TABLE CacLuotGuiXe(
	ID_LuotGui CHARACTER(5) NOT NULL,
	ID_TheTu CHARACTER(5) NOT NULL,
	ID_BaoVe CHARACTER(5) NOT NULL,
	ThoiGianVao TIMESTAMP NOT NULL,
	ThoiGianRa TIMESTAMP NOT NULL,
	CONSTRAINT pk_luotgui PRIMARY KEY(ID_LuotGui),
	CONSTRAINT fk_cacluotgui_thetu FOREIGN KEY(ID_TheTu) REFERENCES TheTu(ID_TheTu) ON DELETE CASCADE,
	CONSTRAINT fk_cacluotgui_baove FOREIGN KEY(ID_BaoVe) REFERENCES BaoVe(ID_BaoVe)
);

